"""Prompts used by the LLM nodes in AetherDeploy.

Prompt architecture
-------------------
AetherDeploy uses two complementary LLM passes during proposal generation:

1. **Cost optimization pass** (``COST_OPTIMIZE_SYSTEM``)
   The LLM receives the matrix-selected services AND the full alternatives
   catalog with cost bounds and constraint rules.  It replaces each service
   with the cheapest valid option, returning ``service_overrides``.

2. **Architecture review pass** (``ARCHITECTURE_REVIEW_SYSTEM``)
   The LLM enriches the (now cost-optimized) proposal with security notes,
   scalability notes, and a brief rationale.  It cannot change services at
   this stage — only add commentary.

Both passes are merged into a single LLM call (``COST_OPTIMIZE_SYSTEM``
already requests all review fields) to keep latency minimal.
"""
from __future__ import annotations

import json


# ---------------------------------------------------------------------------
# Pass 1 + 2 combined: cost optimization AND architecture review
# ---------------------------------------------------------------------------

COST_OPTIMIZE_SYSTEM = """\
You are AetherDeploy, a cloud architect specializing in cost optimization.

## Your objectives (in priority order)

1. **Minimize cost** — For each proposed service, check the ``service_catalog``
   and replace it with the cheapest valid alternative.
2. **Respect constraints** — An option is invalid if:
   - Any hint from its ``excludes`` list is present in ``project_hints``.
   - Its ``requires`` list is non-empty and NONE of those hints appear in
     ``project_hints``.
3. **Review security and scalability** — Add concise notes after selecting
   services.

## Selection algorithm (apply per service purpose)

```
valid_options = [
    o for o in catalog[purpose]
    if not any(h in project_hints for h in o.excludes)
    and (not o.requires or any(h in project_hints for h in o.requires))
]
chosen = min(valid_options, key=lambda o: o.cost_high)
```

If no alternative exists for a purpose, keep the matrix default unchanged
(do not emit a service_override for it).

## Output — return ONLY valid JSON, no markdown, no extra text

```json
{
  "service_overrides": [
    {
      "purpose": "<purpose string — must match a proposed service's purpose>",
      "service": "<service name from catalog>",
      "resource": "<terraform resource from catalog>",
      "justification": "<why this is cheapest AND fits the project — max 150 chars>",
      "cost_range": "<e.g. '~$0-50'>",
      "saving_vs_default": "<e.g. 'saves ~$50/month vs Aurora' — empty string if no saving>"
    }
  ],
  "rationale": "<executive summary of cost decisions — max 300 chars>",
  "security_notes": ["<max 3 strings>"],
  "scalability_notes": ["<max 3 strings>"]
}
```

Rules:
- Emit a service_override ONLY when you select a DIFFERENT service than the
  matrix default (same service = no override needed).
- All strings must be in the same language as the user's instruction.
- Never hallucinate services not in the catalog.
"""

# ---------------------------------------------------------------------------
# Legacy review prompt (kept for backward compatibility with other callers)
# ---------------------------------------------------------------------------

ARCHITECTURE_REVIEW_SYSTEM = """\
You are AetherDeploy, a senior, prudent cloud architect.

Goal:
- Review a deployment proposal generated by provider rules.
- Improve the criteria, do not invent services outside the received proposal.
- Maintain Human-in-the-Loop: /init analyses, /plan previews Terraform, /deploy applies.

Environment rules:
- local: Docker/Docker Compose, no real cloud.
- feature: ephemeral environment to validate changes; for AWS, Terraform points to LocalStack.
- prod: real cloud infrastructure with real credentials and remote backend if applicable.

Criteria:
- Favor security by default, reasonable cost, basic observability, and simple scalability.
- If uncertain, express risk as a note; do not present it as fact.
- Do not recommend applying changes without a prior plan.

Return exclusively JSON with these keys:
- rationale: brief string, maximum 900 characters.
- security_notes: string[] with 0 to 3 notes.
- scalability_notes: string[] with 0 to 3 notes.
"""

TOPOLOGY_REASONING_SYSTEM = """\
Topology complement:
- The analyser classified this project with a complexity profile.
- Consider the profile to validate that the proposed resources are appropriate.
- If the profile suggests low scale (nano/micro), avoid over-provisioning.
- If the profile suggests high scale (large/enterprise), verify observability and HA.
"""


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def cost_optimize_user_prompt(
    *,
    instruction: str,
    provider: str,
    region: str,
    environments: list[str],
    proposed_services: list[dict],
    service_catalog: dict,
    project_hints: list[str],
    profile: str | None,
    service_count: int | None,
    language: str,
    frameworks: list[str],
) -> str:
    """Builds the user message for the combined cost-optimization + review pass.

    Parameters
    ----------
    instruction:
        Raw user instruction (e.g. "deploy my FastAPI app to feature env").
    provider:
        Cloud provider key (e.g. ``"aws"``).
    region:
        Target region (e.g. ``"us-east-1"``).
    environments:
        List of target environments (e.g. ``["feature", "prod"]``).
    proposed_services:
        List of dicts with keys ``purpose``, ``service``, ``resource``,
        ``cost`` — the matrix-default services before optimization.
    service_catalog:
        The ``SERVICE_ALTERNATIVES`` dict from ``providers.aws.services``.
        Serialized to JSON so the LLM can reason over it directly.
    project_hints:
        Detected project signals (e.g. ``["has-database", "api-only"]``).
    profile:
        Complexity profile string or ``None`` (e.g. ``"micro"``).
    service_count:
        Number of detected services, or ``None``.
    language:
        Primary programming language.
    frameworks:
        Detected frameworks.
    """
    env_text = ", ".join(environments) if environments else "prod"
    framework_text = ", ".join(frameworks) if frameworks else "none detected"
    hints_text = ", ".join(project_hints) if project_hints else "none"
    profile_text = profile or "unknown"
    service_count_text = str(service_count) if service_count is not None else "unknown"

    proposed_text = json.dumps(proposed_services, ensure_ascii=False)
    catalog_text = json.dumps(service_catalog, ensure_ascii=False)

    return (
        f"User instruction: {instruction}\n"
        f"Provider: {provider.upper()} | Region: {region} | "
        f"Environments: {env_text}\n"
        f"Stack: {language} | Frameworks: {framework_text}\n"
        f"Complexity profile: {profile_text} | Services detected: {service_count_text}\n"
        f"Project hints: {hints_text}\n"
        "\n"
        f"Matrix-proposed services (before optimization):\n{proposed_text}\n"
        "\n"
        f"Service catalog (alternatives with cost bounds and constraints):\n{catalog_text}\n"
        "\n"
        "Apply the selection algorithm, emit service_overrides for any service "
        "you replace, and return the full JSON response."
    )


def architecture_review_user_prompt(
    *,
    instruction: str,
    action: str,
    provider: str,
    region: str,
    environments: list[str],
    services: str,
    language: str,
    frameworks: list[str],
    profile: str | None = None,
    service_count: int | None = None,
    all_hints: list[str] | None = None,
) -> str:
    """Builds the user message for the legacy architecture review pass.

    Used as fallback when the cost-optimization path is not active.
    """
    framework_text = ", ".join(frameworks) if frameworks else "none detected"
    env_text = ", ".join(environments) if environments else "prod"

    topology_lines = ""
    if profile is not None:
        topology_lines += f"Complexity profile: {profile}\n"
    if service_count is not None:
        topology_lines += f"Number of detected services: {service_count}\n"
    if all_hints:
        topology_lines += f"Detected signals: {', '.join(all_hints)}\n"

    return (
        "Review this deployment proposal.\n"
        f"User instruction: {instruction}\n"
        f"Requested command: /{action}\n"
        f"Detected stack: {language}; frameworks: {framework_text}\n"
        f"Target environments: {env_text}\n"
        f"Provider: {provider}; region: {region}\n"
        f"Proposed services: {services}\n"
        + topology_lines
        + "Respond with valid JSON following exactly the system schema."
    )
