"""HCL generators for application secret resources (MEJORAS.md §3.3).

Emit Terraform that **declares** the secret in a cloud-native vault. The
actual value never lives in the generated HCL: ``aws_secretsmanager_secret``
creates the container, the value is written separately by
:func:`secrets.provisioner.provision_aws_secret_values` (via boto3
``PutSecretValue``) so Terraform state stays free of plaintext credentials.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .detector import SecretSpec


_AWS_HEADER = """# Generated by AetherDeploy (MEJORAS.md §3.3) — do not edit by hand.
# Secret values are written via boto3 PutSecretValue, never via Terraform.

"""


def generate_aws_secrets_tf(
    specs: Iterable[SecretSpec],
    project_name: str,
    environment: str,
) -> str:
    """Returns HCL for `aws_secretsmanager_secret` per spec.

    Resource names use the spec's ``aws_resource_name`` so they are stable
    across regenerations and friendly to ``terraform import``. The Secrets
    Manager *name* is scoped by project + env so two AetherDeploy projects in
    the same account cannot collide.
    """
    specs = list(specs)
    if not specs:
        return ""

    chunks: list[str] = [_AWS_HEADER]
    for spec in specs:
        secret_name = f"{project_name}/{environment}/{spec.name.lower()}"
        chunks.append(
            "resource \"aws_secretsmanager_secret\" "
            f'"{spec.aws_resource_name()}" {{\n'
            f'  name        = "{secret_name}"\n'
            f'  description = "{spec.name} for {project_name} ({environment}) — '
            f'declared in {spec.source.name}"\n'
            "  tags = {\n"
            f'    "aetherdeploy:project" = "{project_name}"\n'
            f'    "aetherdeploy:env"     = "{environment}"\n'
            f'    "aetherdeploy:key"     = "{spec.name}"\n'
            "  }\n"
            "}\n"
        )

    # Outputs only the ARNs so consumers (Lambda/ECS task role) can grant
    # ``secretsmanager:GetSecretValue`` on a known set of resources.
    chunks.append("\n")
    chunks.append(
        "output \"aetherdeploy_secret_arns\" {\n"
        "  description = \"ARNs of every secret AetherDeploy provisioned.\"\n"
        "  value = {\n"
    )
    for spec in specs:
        chunks.append(
            f'    "{spec.name}" = aws_secretsmanager_secret.{spec.aws_resource_name()}.arn\n'
        )
    chunks.append("  }\n}\n")

    return "".join(chunks)


def generate_secrets_tf(
    provider: str,
    specs: Iterable[SecretSpec],
    project_name: str,
    environment: str,
) -> str:
    """Provider-dispatched entry point.

    GCP (Secret Manager) and Azure (Key Vault) generation is not implemented
    yet — those providers return an empty string and the operator can drop in
    handcrafted HCL until parity ships.
    """
    if provider.lower() == "aws":
        return generate_aws_secrets_tf(specs, project_name, environment)
    return ""


def write_secrets_tf(
    content: str,
    tf_dir: Path,
    filename: str = "secrets.tf",
) -> Path | None:
    """Writes ``content`` to ``tf_dir/filename`` and returns the path written.

    Empty content is a no-op (callers do not need to gate on detection emptiness).
    """
    if not content:
        return None
    tf_dir.mkdir(parents=True, exist_ok=True)
    target = tf_dir / filename
    target.write_text(content, encoding="utf-8")
    return target
